version: '3.8'

services:
  couchdb:
    image: couchdb:3
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-admin}
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - car_network

  car-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8050:8050"
    environment:
      - COUCHDB_URL=${COUCHDB_URL:-http://admin:admin@couchdb:5984/}
    depends_on:
      - couchdb
    volumes:
      - ./logs:/app/logs
    networks:
      - car_network

  data-generator:
    build:
      context: .
      dockerfile: Dockerfile.data
    environment:
      - COUCHDB_URL=${COUCHDB_URL:-http://admin:admin@couchdb:5984/}
    depends_on:
      - couchdb
    volumes:
      - ./logs:/app/logs
    entrypoint: ["python", "generate_data.py"]
    restart: "no"   # Run once and stop
    networks:
      - car_network

volumes:
  couchdb_data:

networks:
  car_network:
    driver: bridge
