version: '3.8'
services:
  couchdb:
    image: couchdb:3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data

  car-dashboard:
    build: .
    ports:
      - "8050:8050"
    environment:
      - COUCHDB_URL=http://admin:admin@couchdb:5984/
    depends_on:
      - couchdb
    volumes:
      - ./logs:/app/logs

volumes:
  couchdb_data: