version: '3.8'

services:
  couchdb:
    image: couchdb:3
    container_name: couchdb
    environment:
      COUCHDB_USER: ${COUCHDB_USER:-admin}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD:-admin}
      COUCHDB_CLUSTER_N: 1
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - car_network

  couchdb-init:
    image: curlimages/curl:latest
    container_name: couchdb-init
    depends_on:
      - couchdb
    entrypoint: >
      sh -c "
        echo 'Waiting for CouchDB to be ready...' &&
        sleep 5 &&
        until curl -s -u ${COUCHDB_USER:-admin}:${COUCHDB_PASSWORD:-admin} http://couchdb:5984; do
          echo 'Still waiting for CouchDB...';
          sleep 2;
        done &&
        echo 'Creating _users database if it does not exist...' &&
        curl -sf -X PUT -u ${COUCHDB_USER:-admin}:${COUCHDB_PASSWORD:-admin} http://couchdb:5984/_users || true
      "
    networks:
      - car_network

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - car_network

  car-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: car-dashboard
    ports:
      - "8050:8050"
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-admin}
      - COUCHDB_HOST=couchdb
      - COUCHDB_PORT=5984
      - COUCHDB_URL=http://${COUCHDB_USER:-admin}:${COUCHDB_PASSWORD:-admin}@couchdb:5984/
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=car_metrics
    depends_on:
      - couchdb
      - couchdb-init
      - influxdb
    networks:
      - car_network

  data-generator:
    build:
      context: .
      dockerfile: Dockerfile.data
    container_name: data-generator
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-admin}
      - COUCHDB_HOST=couchdb
      - COUCHDB_PORT=5984
      - COUCHDB_URL=http://${COUCHDB_USER:-admin}:${COUCHDB_PASSWORD:-admin}@couchdb:5984/
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=car_metrics
    depends_on:
      - couchdb
      - couchdb-init
      - influxdb
    entrypoint: ["python", "generate_data.py"]
    networks:
      - car_network

volumes:
  couchdb_data:
  influxdb_data:

networks:
  car_network:
    driver: bridge
