version: '3.8'

services:
  couchdb:
    image: couchdb:3
    container_name: couchdb
    environment:
      COUCHDB_USER: ${COUCHDB_USER:-admin}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD:-admin}
      COUCHDB_CLUSTER_N: 1
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - car_network

  couchdb-init:
    image: curlimages/curl:latest
    container_name: couchdb-init
    depends_on:
      - couchdb
    entrypoint: >
      sh -c "
        echo 'Waiting for CouchDB to be ready...' &&
        sleep 5 &&
        until curl -s -u ${COUCHDB_USER:-admin}:${COUCHDB_PASSWORD:-admin} http://couchdb:5984; do
          echo 'Still waiting for CouchDB...';
          sleep 2;
        done &&
        echo 'Creating _users database if it does not exist...' &&
        curl -sf -X PUT -u ${COUCHDB_USER:-admin}:${COUCHDB_PASSWORD:-admin} http://couchdb:5984/_users || true
        -X PUT -u ${COUCHDB_USER:-admin}:${COUCHDB_PASSWORD:-admin} http://couchdb:5984/_users
      "
    networks:
      - car_network

  car-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8050:8050"
    environment:
      - COUCHDB_URL=${COUCHDB_URL:-http://admin:admin@couchdb:5984/}
    depends_on:
      - couchdb
      - couchdb-init
    volumes:
      - ./logs:/app/logs
    networks:
      - car_network

  data-generator:
    build:
      context: .
      dockerfile: Dockerfile.data
    environment:
      - COUCHDB_URL=${COUCHDB_URL:-http://admin:admin@couchdb:5984/}
    depends_on:
      - couchdb
      - couchdb-init
    volumes:
      - ./logs:/app/logs
    entrypoint: ["python", "generate_data.py"]
    networks:
      - car_network

volumes:
  couchdb_data:

networks:
  car_network:
    driver: bridge
