apiVersion: v1
kind: ConfigMap
metadata:
  name: car-config
  namespace: car-app
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
data:
  REFRESH_INTERVAL: "10"
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-config
  namespace: car-app
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
    kustomize.toolkit.fluxcd.io/disableNameSuffixHash: "true"
data:
  docker.ini: |
    [couchdb]
    single_node = true

    [httpd]
    bind_address = 0.0.0.0

    [chttpd]
    bind_address = 0.0.0.0

    [admins]
    admin = admin

    [secret]
    cookie = supersecret

    [log]
    level = info
---