apiVersion: v1
kind: ConfigMap
metadata:
  name: car-config
  namespace: car-app
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
data:
  REFRESH_INTERVAL: "10"
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-config
  namespace: car-app
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
    kustomize.toolkit.fluxcd.io/disableNameSuffixHash: "true"
data:
  docker.ini: |
    [couchdb]
    single_node = ${SINGLE_NODE}

    [httpd]
    bind_address = 0.0.0.0

    [chttpd]
    bind_address = 0.0.0.0

    [admins]
    ${COUCHDB_USER} = ${COUCHDB_PASSWORD}

    [secret]
    cookie = ${COUCHDB_SECRET}

    [log]
    level = info
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config-template
  namespace: car-logs
data:
  kibana.yml.template: |
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["http://elasticsearch.car-logs.svc.cluster.local:9200"]

    xpack.security.encryptionKey: "${XPACK_SECURITY_ENCRYPTIONKEY}"
    xpack.encryptedSavedObjects.encryptionKey: "${ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY}"
    xpack.reporting.encryptionKey: "${REPORTING_ENCRYPTIONKEY}"
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: car-app
  labels:
    app: fluent-bit
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
    kustomize.toolkit.fluxcd.io/disableNameSuffixHash: "true"
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

    [INPUT]
        Name              tail
        Path              /logs/app/*.log
        Tag               car-app
        DB                /var/log/flb_car_app.db
        Parser            docker
        Refresh_Interval  5
        Read_From_Head    True

    [INPUT]
        Name              tail
        Path              /logs/data/*.log
        Tag               car-data
        DB                /var/log/flb_car_data.db
        Parser            docker
        Refresh_Interval  5
        Read_From_Head    True

    [FILTER]
        Name                kubernetes
        Match               car-*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     car-
        Merge_Log           On
        Keep_Log            Off

    [OUTPUT]
        Name               es
        Match              car-*
        Host               elasticsearch.car-logs.svc.cluster.local
        Port               9200
        Logstash_Format    On
        Logstash_Prefix    car
        Retry_Limit        False

  parsers.conf: |
    [PARSER]
        Name         docker
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S
        Time_Keep    On
        Decode_Field_As   escaped    log  do_next
        Decode_Field_As   json       log
