apiVersion: v1
kind: ConfigMap
metadata:
  name: car-config
  namespace: car-app
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
data:
  REFRESH_INTERVAL: "10"
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-config
  namespace: car-app
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
    kustomize.toolkit.fluxcd.io/disableNameSuffixHash: "true"
data:
  docker.ini: |
    [couchdb]
    single_node = ${SINGLE_NODE}

    [httpd]
    bind_address = 0.0.0.0

    [chttpd]
    bind_address = 0.0.0.0

    [admins]
    ${COUCHDB_USER} = ${COUCHDB_PASSWORD}

    [secret]
    cookie = ${COUCHDB_SECRET}

    [log]
    level = info
--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: car-logs
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    server.port: 5601
    elasticsearch.hosts: [ "http://elasticsearch.car-logs.svc.cluster.local:9200" ]
    xpack.security.encryptionKey: "a-32-byte-long-key-for-dev-only!!"
    xpack.encryptedSavedObjects.encryptionKey: "another-32-byte-key-for-dev-env!"
    xpack.reporting.encryptionKey: "yet-another-32-byte-key-for-dev!!"
    xpack.reporting.kibanaServer.hostname: "localhost"
    xpack.screenshotting.browser.chromium.disableSandbox: true
    # Optional: Disable Fleet and other UI features
    xpack.fleet.enabled: false
    xpack.securitySolution.enabled: false
    xpack.uptime.enabled: false
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: car-app
  labels:
    app: fluent-bit
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
    kustomize.toolkit.fluxcd.io/disableNameSuffixHash: "true"
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        30
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

    # Tail application logs
    [INPUT]
        Name              tail
        Path              /logs/app/*.log
        Tag               car_app
        DB                /fluent-bit/db/flb_car_app.db
        Parser            docker
        Buffer_Chunk_Size 1M
        Buffer_Max_Size   5M
        Mem_Buf_Limit     10M
        Refresh_Interval  5
        Read_From_Head    True

    # Tail data generator logs
    [INPUT]
        Name              tail
        Path              /logs/data/*.log
        Tag               car_data
        DB                /fluent-bit/db/flb_car_data.db
        Parser            docker
        Buffer_Chunk_Size 1M
        Buffer_Max_Size   5M
        Mem_Buf_Limit     10M
        Refresh_Interval  5
        Read_From_Head    True

    # Tail Kubernetes container logs
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Tag               kube.var.log.containers.*
        DB                /fluent-bit/db/flb_kube.db
        Parser            docker
        Buffer_Chunk_Size 1M
        Buffer_Max_Size   5M
        Mem_Buf_Limit     10M
        Refresh_Interval  5
        Read_From_Head    False

    # Rename `log` → `message` to avoid ES mapping conflicts
    [FILTER]
        Name   lua
        Match  *
        script rename_log.lua
        call   rename

    # Output to Elasticsearch for pod logs
    [OUTPUT]
        Name               es
        Match              kube.var.log.containers.*
        Host               elasticsearch.car-logs.svc.cluster.local
        Port               9200
        Logstash_Format    On
        Logstash_Prefix    kubernetes-logs
        Replace_Dots       On
        Retry_Limit        False
        Suppress_Type_Name On

    # Output to Elasticsearch for app & generator logs
    [OUTPUT]
        Name               es
        Match              car_*
        Host               elasticsearch.car-logs.svc.cluster.local
        Port               9200
        Logstash_Format    On
        Logstash_Prefix    file-logs
        Replace_Dots       On
        Retry_Limit        False
        Suppress_Type_Name On

  parsers.conf: |
    [PARSER]
        Name         docker
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep    On
        Decode_Field_As   escaped    log  do_next
        Decode_Field_As   json       log

  rename_log.lua: |
    function rename(tag, timestamp, record)
      if record["log"] ~= nil then
        record["log_message"] = record["log"]
        record["log"] = nil
      end
      return 1, timestamp, record
    end
