apiVersion: v1
kind: Namespace
metadata:
  name: car-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: car-config
  namespace: car-app
  annotations:
    kustomize.config.k8s.io/dependsOn: |
      - kind: Namespace
        name: car-app
data:
  REFRESH_INTERVAL: "30"

