apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
  labels:
    app: fluent-bit
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name          tail
        Path          /app/logs/app.log
        Tag           car-dashboard-log
        DB            /var/log/flb_k8s.db
        Parser        docker
        Refresh_Interval 5

    [OUTPUT]
        Name  es
        Match *
        Host  elasticsearch
        Port  9200
        Index car-dashboard-logs
        Type  _doc

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S
        Time_Keep   On
        Decode_Field_As   escaped    log  do_next
        Decode_Field_As   json       log