apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: car-logs
  labels:
    app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

    [INPUT]
        Name          tail
        Path          /logs/app/*.log
        Tag           car-app
        DB            /var/log/flb_car_app.db
        Parser        docker
        Refresh_Interval 5

    [INPUT]
        Name          tail
        Path          /logs/data/*.log
        Tag           car-data
        DB            /var/log/flb_car_data.db
        Parser        docker
        Refresh_Interval 5
    
    [FILTER]
        Name                kubernetes
        Match               car-*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     car-
        Merge_Log           On
        Keep_Log            Off

    [OUTPUT]
        Name  es
        Match *
        Host  elasticsearch
        Port  9200
        # Use tag dynamically in index name for separation:
        Index car-${tag}-logs
        Type  _doc

  parsers.conf: |
    [PARSER]
        Name         docker
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S
        Time_Keep    On
        Decode_Field_As   escaped    log  do_next
        Decode_Field_As   json       log
--- 
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: car-logs
  labels:
    app: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit-sa
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:2.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2020
          resources:
            limits:
              memory: 256Mi
              cpu: 200m
            requests:
              memory: 128Mi
              cpu: 100m
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 2020
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2
          volumeMounts:
            - name: car-app-pvc
              mountPath: /logs/app
              readOnly: true
            - name: car-data-pvc
              mountPath: /logs/data
              readOnly: true
            - name: config
              mountPath: /fluent-bit/etc/
              readOnly: true
            - name: var-run
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: fluent-bit-config
        - name: car-app-pvc
          persistentVolumeClaim:
            claimName: car-app-pvc
        - name: car-data-pvc
          persistentVolumeClaim:
            claimName: car-data-pvc
        - name: var-run
          hostPath:
            path: /var/run/secrets/kubernetes.io/serviceaccount
            type: Directory
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit-sa
  namespace: car-logs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-role
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-binding
roleRef:
  kind: ClusterRole
  name: fluent-bit-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fluent-bit-sa
    namespace: car-logs
