apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: car-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5601"
        fluxcd.io/automated: "true"
    spec:
      containers:
        - name: kibana
          image: docker.io/library/kibana:9.0.2
          ports:
            - containerPort: 5601
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
      volumes:
        - name: kibana-config
          configMap:
            name: kibana-config

--- 
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: car-logs
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
      nodePort: 30601
