apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: car-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.13.0
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch.car-logs.svc.cluster.local:9200
          readinessProbe:
            httpGet:
              path: /
              port: 5601
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 5601
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: car-logs
spec:
  selector:
    app: kibana
  ports:
    - name: http
      port: 80
      targetPort: 5601
      protocol: TCP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kibana
  namespace: car-logs
spec:
  to:
    kind: Service
    name: kibana
  port:
    targetPort: http
  tls:
    termination: edge
