apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: car-logs
  labels:
    app: kibana
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
    kustomize.toolkit.fluxcd.io/disableNameSuffixHash: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.13.0
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch.car-logs.svc.cluster.local:9200
          readinessProbe:
            httpGet:
              path: /
              port: 5601
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 5601
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: car-logs
  labels:
    app: kibana
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
    kustomize.toolkit.fluxcd.io/disableNameSuffixHash: "true"
spec:
  selector:
    app: kibana
  ports:
    - name: http
      port: 80
      targetPort: 5601
      protocol: TCP
