apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - configMap.yaml
  - secret.yaml
  - volume.yaml
  - couchdb.yaml
  - influxdb.yaml
  - flask-apps.yaml
  - fluent-bit.yaml
  - elasticsearch.yaml
  - kibana.yaml
  - chronograf.yaml
