apiVersion: v1
kind: Secret
metadata:
  name: couchdb-secret
  namespace: car-app
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
type: Opaque
data:
  COUCHDB_USER: YWRtaW4=         # admin
  COUCHDB_PASSWORD: YWRtaW4=     # admin
  COUCHDB_SECRET: c3VwZXJzZWNyZXQ=  # supersecret
