apiVersion: v1
kind: Secret
metadata:
  name: couchdb-secret
  namespace: car-app
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
type: Opaque
data:
  COUCHDB_USER: YWRtaW4=         # admin
  COUCHDB_PASSWORD: YWRtaW4=     # admin
  COUCHDB_SECRET: c3VwZXJzZWNyZXQ=  # supersecret
--- 
apiVersion: v1
kind: Secret
metadata:
  name: kibana-encryption-keys
  namespace: car-logs
type: Opaque
data:
  xpack_security_encryptionKey: eW91ci1zZWN1cmUtcmFuZG9tLXN0cmluZy0x
  xpack_encryptedSavedObjects_encryptionKey: eW91ci1zZWN1cmUtcmFuZG9tLXN0cmluZy0y
  xpack_reporting_encryptionKey: eW91ci1zZWN1cmUtcmFuZG9tLXN0cmluZy0z
