apiVersion: v1
kind: Secret
metadata:
  name: couchdb-secret
  namespace: car-app
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
type: Opaque
data:
  COUCHDB_USER: YWRtaW4=         # admin
  COUCHDB_PASSWORD: YWRtaW4=     # admin
  COUCHDB_SECRET: c3VwZXJzZWNyZXQ=  # supersecret
--- 
apiVersion: v1
kind: Secret
metadata:
  name: kibana-encryption-keys
  namespace: car-logs
type: Opaque
data:
  xpack_security_encryptionKey: ZnNHSXBmU3pEcnFjeVZ1MEZXUzRRcUpEUjNSblNucWc=
  xpack_encryptedSavedObjects_encryptionKey: M3plcUxMSkFxckJ3bFJ6U3RsRnF6Z0JLSHRnOEVXVkI=
  xpack_reporting_encryptionKey: dE5LMkV5R1RjMkpoNURReVkyRnJaVzVuT1ZKNmQwOWk=
