apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf
  namespace: car-logs
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
        - name: telegraf
          image: telegraf:1.28-alpine
          imagePullPolicy: IfNotPresent
          args:
            - "--config"
            - "/etc/telegraf/telegraf.conf"
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
          resources:
            limits:
              memory: 150Mi
              cpu: 150m
            requests:
              memory: 100Mi
              cpu: 100m
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
      volumes:
        - name: config
          configMap:
            name: telegraf-config
