apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: car-app-pvc
  namespace: car-app
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: car-data-pvc
  namespace: car-app
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fluent-bit-logs-pvc
  namespace: car-logs
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
spec:
  accessModes:
    - ReadWriteMany  
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-pvc
  namespace: car-app
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  namespace: car-logs
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: car-logs
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kibana-pvc
  namespace: car-logs
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
